repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: requirements-txt-fixer
        description: sorts entries in requirements.txt
      - id: check-docstring-first
        description: checks a common error of defining a docstring after code
      - id: end-of-file-fixer
        description: makes sure files end in a newline and only a newline
      - id: trailing-whitespace
        description: trims trailing whitespace
        # md: To preserve Markdown hard linebreaks
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--line-length=180", "--profile=black"]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.11.0
    hooks:
      - id: black
        args: ["--line-length=180"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        # E265: Block comment should start with '# '
        # E266: Too many leading '#' for block comment
        # E501: Line too long
        # E731: Do not assign a lambda expression, use a def
        # F401: Module imported but unused
        # W503: Line break occurred before a binary operator (Because of black)
        # W504: Line break occurred after a binary operator (Because of black)
        args: ["--ignore=E265,E266,E501,E731,F401,W503,W504"]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.2
    hooks:
      - id: nbstripout

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-isort
        args: ["--line-length=140", "--profile=black"]
      - id: nbqa-black
        args: ["--line-length=140"]
      - id: nbqa-flake8
        # E265: Block comment should start with '# '
        # E266: Too many leading '#' for block comment
        # E501: Line too long
        # E731: Do not assign a lambda expression, use a def
        # F401: Module imported but unused
        # F821: Undefined name (Because of constants from other scripts)
        # W503: Line break occurred before a binary operator (Because of black)
        # W504: Line break occurred after a binary operator (Because of black)
        args: ["--ignore=E265,E266,E501,E731,F401,F821,W503,W504"]
